export const projects = [
  {
    title: "ZenTab",
    desc: "The minimalist new tab replacement for Chrome.",
    image: "/projects/zentab-main.png",
    techStack: ["HTML", "CSS", "JavaScript", "Chrome Extension"],
    link: "https://github.com/rbrickmn/zentab",
    type: "chrome-extension",
  },
  {
    title: "Regex Playground",
    desc: "A playground for regex",
    image: "/projects/regexpg.png",
    techStack: ["React", "Tailwind CSS", "Vite"],
    link: "https://regex-playground-gray.vercel.app/",
    type: "web-app",
  },
  {
    title: "SyntaxSprint",
    desc: "The typing game for programmers!",
    image: "/projects/syntaxsprint.gif",
    techStack: ["React", "CSS", "Marked.js", "Vite"],
    link: "https://syntaxsprint-app.vercel.app/",
    type: "web-app",
  },
  {
    title: "MixMaster",
    desc: "Create Spotify playlists with ease.",
    image: "/projects/mixmaster.gif",
    techStack: ["React", "CSS", "Spotify API"],
    link: "https://github.com/rbrickmn/mixmaster-app",
    type: "web-app",
  },
  {
    title: "MouseTrack",
    desc: "Mouse performance analyzer",
    image: "/projects/mouse-track-screenshot.png",
    techStack: ["HTML", "CSS", "JavaScript"],
    link: "https://mousetrack-app.vercel.app/",
    type: "web-app",
  },
  {
    title: "MarkdownLens (BETA)",
    desc: "A simple, lightweight markdown editor/viewer.",
    image: "/projects/mdlens-screenshot.png",
    techStack: ["React", "Redux", "Giphy API"],
    link: "https://md-lens.vercel.app/",
    type: "web-app",
  },
  {
    title: "T.L. Hanna - Tidings 2019",
    desc: "Lead editor for T.L. Hanna High School's 2019 Yearbook",
    image: "/projects/tlh.jpg",
    techStack: [
      "Photography",
      "Photo Editing",
      "Digital Asset Management (DAM)",
      "Leadership",
    ],
    link: "https://tlhanna.anderson5.net/",
    type: "photography",
  },
  {
    title: "T.L. Hanna - Tidings 2020",
    desc: "Lead editor for T.L. Hanna High School's 2020 Yearbook",
    image: "/projects/tlh.jpg",
    techStack: [
      "Photography",
      "Photo Editing",
      "Digital Asset Management (DAM)",
      "Leadership",
    ],
    link: "https://tlhanna.anderson5.net/",
    type: "photography",
  },
];
